name: mansOS Angular CI/CD

on:
  push:
    branches: [ testing ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 12.8
      uses: actions/setup-node@v1
      with:
        python-version: '12.8'
    - name: Install Dependencies
      run: |
        npm ci
  deploy:
    runs-on: ubuntu-latest
    name: Deployment to server
    steps:
    - name: SSH to remote server
      uses: appleboy/ssh-action@master 
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        username: ${{ secrets.USERNAME }}
        script: |
          cd /home/mangos/angular/mangOS-admin
          ./script.sh
