name: Build and Deploy Mangos on main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Debug Secrets
      run: |
        echo "Checking secrets configuration"
        if [ -z "${{ secrets.SERVER_HOST_MAIN }}" ]; then
          echo "SERVER_HOST is not set"
        fi
        if [ -z "${{ secrets.SERVER_USER_MAIN }}" ]; then
          echo "SERVER_USER is not set"
        fi

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_MAIN }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SERVER_HOST_MAIN }} >> ~/.ssh/known_hosts
        
    - name: Test SSH Connection
      run: |
        ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER_MAIN }}@${{ secrets.SERVER_HOST_MAIN }} "echo 'SSH connection successful!'"

    - name: Prepare Server Directory (Main)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST_MAIN }}
        username: ${{ secrets.SERVER_USER_MAIN }}
        key: ${{ secrets.SSH_PRIVATE_KEY_MAIN }}
        script: |
          rm -rf /home/ubuntu/mangos/frontend/prod/*
          mkdir -p /home/ubuntu/mangos/frontend/prod

    - name: Deploy Build Files
      run: |
        rsync -avz \
          -e "ssh -i ~/.ssh/id_rsa" \
          dist/* ${{ secrets.SERVER_USER_MAIN }}@${{ secrets.SERVER_HOST_MAIN }}:/home/ubuntu/mangos/frontend/prod/